name: Mint more NFTs
on: [workflow_dispatch]
jobs:
  mint:
    name: Mint NFTs
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2
      
      - name: ❄️ Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with: 
          file_name: .env
          envkey_INFURA_PROJECT_ID: ${{secrets.INFURA_PROJECT_ID}}
          envkey_KEY_MNEMONIC: ${{secrets.KEY_MNEMONIC}}
          envkey_SERVICE_URL: ${{secrets.SERVICE_URL}}

      - name: Use the correct Truffle file
        run: |
          rm truffle-config.js
          mv truffle-config-ci.js truffle-config.js

      - name: Truffle Mint
        run: node_modules/.bin/truffle exec devops/test.js --network rinkeby

      - name: Checkout Lambda repo
        uses: actions/checkout@v2
        with:
          repository: silviopaganini/nft-market-service
          path: lambda

      - name: Update DB
        run: |
          cd lambda
          rm db/index.ts
          mv ../db.ts db/index.ts

          git config --global credential.helper store
          ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://${{secrets.GH_TOKEN}}:x-oauth-basic@github.com`n" -NoNewline
          
          git config user.name github-actions
          git config user.email github-actions@github.com

          git checkout -b feature/update-db

          git add .
          git commit -m "update database"
          git push origin feature/update-db

      